dataset: "sift"
topk: 100
num_threads: 10
index_types:
  - index_type: "Flat"
    params: {}
  - index_type: "IVF1024,Flat"
    params:
      nprobe: 16
  - index_type: "HNSW32,Flat"
    params:
      efConstruction: 40
      efSearch: 16